#!/bin/sh

if [ -f /etc/default/jenkins-slave ]; then
	. /etc/default/jenkins-slave
fi
JENKINS_URL=${JENKINS_URL:-http://localhost:8080/}
JENKINS_NODENAME=${JENKINS_NODENAME:-$(hostname)}
JENKINS_CLI=/usr/local/jenkins/jenkins-cli.jar

jenkins_cli() {
	cmd=$1
	java -jar $JENKINS_CLI -s $JENKINS_URL $cmd $JENKINS_NODENAME
}

case "$1" in
start)
	for n in 5 4 3 2 1; do
		jenkins_cli connect-node
		jenkins_cli online-node
		output=$(jenkins_cli get-node)
		if [ $? -eq 0 ]; then
			echo $output|grep 'temporaryOfflineCause' >/dev/null
			if [ $? -ne 0 ]; then
				echo "online command succeeded."
				break;
			fi
		fi
                echo "online command failed."
		sleep 10
	done
	;;
stop)
	;;
connect)
	jenkins_cli connect-node
	;;
disconnect)
	jenkins_cli disconnect-node
	;;
online)
	jenkins_cli online-node
	;;
offline)
	jenkins_cli offline-node
	;;
"")
	jenkins_cli get-node
	;;
*)
	echo "$(basename $0) [start|stop|connect|disconnect|online|offline]"
	;;
esac
